### ISSUE TITLE
在笔记本尺寸小的情况下，四周会有黑边，请教下这个怎么解决

### ISSUE THREAD

**Issue by wangShiBoGT** [qdfudimo/vue3-screen#1]

**Comment by qdfudimo** [comment]
没办法啊，因为大屏原本就在大的屏幕上显示的，有个判断屏幕宽度的，你可以去掉，就和屏幕一样大

**Comment by wangShiBoGT** [comment]
> 没办法啊，因为大屏幕上本来就在大屏幕显示的，屏幕判断内容的，你可以把屏幕和屏幕一样大的

那如果大屏缩小，整体图片都会被缩小，这个怎么整，提BUG了

**Comment by wangShiBoGT** [comment]
整体的地图就被可以拉长缩小了一样

**Comment by wangShiBoGT** [comment]
> 没办法啊，因为大屏幕上本来就在大屏幕显示的，屏幕判断内容的，你可以把屏幕和屏幕一样大的
上下拉的话，echarts图就被压扁了一样

**Comment by qdfudimo** [comment]
你贴图看看

**Comment by wangShiBoGT** [comment]
![image](https://user-images.githubusercontent.com/82799091/201287800-e2d65258-f99d-4594-b11e-96e2ea186fe4.png)
这是宽不变高变到600px以后就成这样了

**Comment by wangShiBoGT** [comment]
> ![image](https://user-images.githubusercontent.com/82799091/201287800-e2d65258-f99d-4594-b11e-96e2ea186fe4.png) 这是宽不变高变到600px以后就成这样了

整个你会发现都是扁的，为了让canvas不模糊，devicePixelRatio加了这个提高清晰度，但是整体的这个还是很扁

**Comment by wangShiBoGT** [comment]
> 你贴图看看

这里

**Comment by qdfudimo** [comment]
都缩小到600px 那不叫大屏嘛 这叫大屏自适应不是小屏自适应啊。而且现在也没时间维护了啊，你有没有什么好的想法啊
